// <auto-generated />
using System;
using BlazorTarefas.Dados;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BlazorTarefa.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dados")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BlazorTarefa.Models.Tarefa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Concluido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("concluido");

                    b.Property<DateTimeOffset?>("ConcluidoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("concluido_em");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<Guid?>("IdPai")
                        .HasColumnType("uuid")
                        .HasColumnName("id_pai");

                    b.HasKey("Id");

                    b.HasIndex("Concluido");

                    b.HasIndex("IdPai");

                    b.ToTable("tarefas", "dados");
                });

            modelBuilder.Entity("BlazorTarefa.Models.Tarefa", b =>
                {
                    b.HasOne("BlazorTarefa.Models.Tarefa", null)
                        .WithMany("SubTarefas")
                        .HasForeignKey("IdPai")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BlazorTarefa.Models.Tarefa", b =>
                {
                    b.Navigation("SubTarefas");
                });
#pragma warning restore 612, 618
        }
    }
}
